<!DOCTYPE html>
<html>

<head>
    <title>Mood Log Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 40px;
        }

        h1 {
            text-align: center;
            color: #333;
            margin-bottom: 20px;
        }

        .header-info {
            text-align: right;
            margin-bottom: 30px;
            font-size: 10px;
            color: #666;
        }

        .header-info span {
            display: block;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        .mood-happy {
            color: #28a745;
        }

        .mood-sad {
            color: #007bff;
        }

        .mood-angry {
            color: #dc3545;
        }

        .mood-excited {
            color: #ffc107;
        }

        .deleted-badge {
            background-color: #6c757d;
            /* grey */
            color: white;
            padding: 3px 6px;
            border-radius: 4px;
            font-size: 0.75em;
            margin-left: 5px;
        }

        .filter-section {
            margin-bottom: 20px;
            padding: 10px;
            border: 1px solid #eee;
            background-color: #f9f9f9;
            border-radius: 5px;
            font-size: 11px;
        }
    </style>
</head>

<body>
    <h1>Mood Log Report</h1>

    <div class="header-info">
        <span>Report Generated By: {{ $userName ?? 'Guest' }}</span>
        <span>Date: {{ $reportDate }}</span>
    </div>

    <div class="filter-section">
        <strong>Applied Filters:</strong><br>
        @if ($filterInfo['start_date'])
            <span>Start Date: {{ $filterInfo['start_date'] }}</span><br>
        @else
            <span>Start Date: N/A</span><br>
        @endif
        @if ($filterInfo['end_date'])
            <span>End Date: {{ $filterInfo['end_date'] }}</span><br>
        @else
            <span>End Date: N/A</span><br>
        @endif
        <span>Show Deleted: {{ $filterInfo['show_deleted'] ? 'Yes' : 'No' }}</span>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Mood</th>
                <th>Note</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($moods as $mood)
                <tr>
                    <td>{{ \Carbon\Carbon::parse($mood->entry_date)->format('Y-m-d') }}</td>
                    <td class="mood-{{ strtolower($mood->mood_type) }}">
                        {{ $mood->mood_type }}
                    </td>
                    <td>{{ $mood->note ?? 'N/A' }}</td>
                    <td>
                        @if ($mood->trashed())
                            Deleted
                        @else
                            Active
                        @endif
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="4">No mood entries found for this report.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>

</html>
